### ISSUE TITLE
Mock tool does not require JSON body

### ISSUE THREAD

**Issue by lkiesow** [Odrec/mockup_api#12]
The path returning the mock tool says it *requires* a JSON request body. It doesn't, does it?

![Screenshot from 2024-07-18 10-42-35](https://github.com/user-attachments/assets/4898e8cc-25c4-47c8-afea-63d02f6f8b3d)

https://github.com/Odrec/mockup_api/blob/b12a9712e1499802cbac8581b802cb1f129c5d97/main.py#L20-L21

**Comment by Odrec** [comment]
As I understand FastAPI uses something called BaseModel from pydantic to validate request data and this uses a JSON format. That's why this is done:

```
class Token(BaseModel):
    token: str
```

But I guess we could get rid of it?

**Comment by dennis531** [comment]
We should read the token as form data, see https://fastapi.tiangolo.com/tutorial/request-forms

![image](https://github.com/user-attachments/assets/48ad75f3-8035-43d6-86a4-292ef74b9727)

**Comment by dennis531** [comment]
The documentation is availble at http://127.0.0.1:8000/docs
