### ISSUE TITLE
Hard-coded tool path

### ISSUE THREAD

**Issue by lkiesow** [Odrec/mockup_api#7]
This doesn't work for the test deployment. It should probably be configurable. Even for the demo tool. That is what the Stud.IP tool should use to access the tool after all.
https://github.com/Odrec/mockup_api/blob/b12a9712e1499802cbac8581b802cb1f129c5d97/main.py#L40-L41

This should point to this tool's API

**Comment by dennis531** [comment]
I recommend to use an environment variable for the host
